const QUERIES = {
  MANAGE_VEHICLE: 'manage-vehicles',
  MANAGE_Details_VEHICLE: 'MANAGE_Details_VEHICLE',
  VEHICLES_TYPES: 'vehicles-types',
  VEHICLES_COLORS: 'vehicles-colors',
  VEHICLES_MODELS: 'vehicles-models',
  VEHICLES_GROUPS: 'vehicles-groups',
  VEHICLES_MAKER: 'vehicles-maker',
  VEHICLES_MAKER_LIST_VALUES: 'VEHICLES_MAKER_LIST_VALUES',
  VEHICLES_ACCOUNT_INFO_PASSWORD: 'VEHICLES_ACCOUNT_INFO_PASSWORD',
  VEHICLES_COLOR_LIST_VALUES: 'VEHICLES_COLOR_LIST_VALUES',
  VEHICLES_MODEL_LIST_VALUES: 'VEHICLES_MODEL_LIST_VALUES',
  VEHICLES_TYPE_LIST_VALUES: 'VEHICLES_TYPE_LIST_VALUES',
  VEHICLES_GROUP_LIST_VALUES: 'VEHICLES_GROUP_LIST_VALUES',
  VEHICLES_ENGINE_TYPE_LIST_VALUES: 'VEHICLES_ENGINE_TYPE_LIST_VALUES',
  VEHICLES_STATION_LIST_VALUES: 'VEHICLES_STATION_LIST_VALUES',

  MAP_STATION_INFO_VALUES: 'MAP_STATION_INFO_VALUES',
  STATION_ROLE_LIST_VALUES: 'STATION_ROLE_LIST_VALUES',
  STATION_PERMISSION_VALUES: 'STATION_PERMISSION_VALUES',



  MANAGE_TERMINAL_LIST_VALUES: 'MANAGE_TERMINAL_LIST_VALUES',
  TERMINAL_LIST_VALUES: 'TERMINAL_LIST_VALUES',

  ALL_PASSENGER_LIST_VALUES: 'ALL_PASSENGER_LIST_VALUES',
  ALL_REGION_LIST_VALUES: 'ALL_REGION_LIST_VALUES',
  ALL_Vehicle_LIST_VALUES: 'ALL_Vehicle_LIST_VALUES',
  ALL_DRIVER_LIST_VALUES: 'ALL_DRIVER_LIST_VALUES',
  ALL_Country_LIST_VALUES: 'ALL_Country_LIST_VALUES',
  ALL_MAINTENSE_STATUS_LIST_VALUES: 'ALL_MAINTENSE_STATUS_LIST_VALUES',
  ALL_Terminal_LIST_VALUES: 'ALL_Terminal_LIST_VALUES',
  ALL_ADS_LIST_VALUES: 'ALL_ADS_LIST_VALUES',
  ALL_ADS_PATH_LIST_VALUES: 'ALL_ADS_PATH_LIST_VALUES',
  ALL_VEHICLES_PATH_LIST_VALUES: 'ALL_VEHICLES_PATH_LIST_VALUES',

  TRIP_LIST_QUERY_TABLE: 'TRIP_LIST_QUERY_TABLE',

  ALL_REGION_Working_LIST_VALUES: 'ALL_REGION__Working_LIST_VALUES',
  ALL_SHIFT_LIST_VALUES: 'ALL_SHIFT_LIST_VALUES',
  ALL_GROUP_BY_REGION_LIST_VALUES: 'ALL_GROUP_BY_REGION_LIST_VALUES',
  WORKING_CARS_DAYS_LIST_VALUES: 'WORKING_CARS_DAYS_LIST_VALUES',


  SETTING_SHIFT_LIST_VALUE:"SETTING_SHIFT_LIST_VALUE",
  SHIT_EDIT_DETSILS:"SHIT_EDIT_DETSILS",

  SETTING_INFRACTION_TYPE_LIST_VALUE:"SETTING_INFRACTION_TYPE_LIST_VALUE",
  SETTING_REASON_CANCEL_LIST_VALUE:"SETTING_REASON_CANCEL_LIST_VALUE",
  SETTING_COUNTRY_LIST_VALUE:"SETTING_COUNTRY_LIST_VALUE",
  SETTING_TIMEZONE_LIST_VALUE:"SETTING_TIMEZONE_LIST_VALUE",
  SETTING_CITY_LIST_VALUE:"SETTING_CITY_LIST_VALUE",
  SETTING_GROUP_LIST_VALUE:"SETTING_GROUP_LIST_VALUE",
  SETTING_Maintenace_STATUS_LIST_VALUE:"SETTING_Maintenace_STATUS_LIST_VALUE",
  SETTING_WORKSHOP_LIST_VALUE:"SETTING_WORKSHOP_LIST_VALUE",
  SETTING_USERTYPE_LIST_VALUE:"SETTING_USERTYPE_LIST_VALUE",
  SETTING_PART_LIST_VALUE:"SETTING_PART_LIST_VALUE",
  SETTING_PART_TYPE_LIST_VALUE:"SETTING_PART_TYPE_LIST_VALUE",
  SETTING_PART_CAR_LIST_VALUE:"SETTING_PART_CAR_LIST_VALUE",



  MANAGE_PATH_LIST_VALUES: 'MANAGE_PATH_LIST_VALUES',
  MANAGE_ADS_LIST_VALUES: 'MANAGE_ADS_LIST_VALUES',
}  

export { QUERIES }
