const QUERIES = {
  MANAGE_VEHICLE: 'manage-vehicles',
  MANAGE_Details_VEHICLE: 'MANAGE_Details_VEHICLE',
  VEHICLES_TYPES: 'vehicles-types',
  VEHICLES_COLORS: 'vehicles-colors',
  VEHICLES_MODELS: 'vehicles-models',
  VEHICLES_GROUPS: 'vehicles-groups',
  VEHICLES_MAKER: 'vehicles-maker',
  VEHICLES_MAKER_LIST_VALUES: 'VEHICLES_MAKER_LIST_VALUES',
  VEHICLES_ACCOUNT_INFO_PASSWORD: 'VEHICLES_ACCOUNT_INFO_PASSWORD',
  VEHICLES_COLOR_LIST_VALUES: 'VEHICLES_COLOR_LIST_VALUES',
  VEHICLES_MODEL_LIST_VALUES: 'VEHICLES_MODEL_LIST_VALUES',
  VEHICLES_TYPE_LIST_VALUES: 'VEHICLES_TYPE_LIST_VALUES',
  VEHICLES_GROUP_LIST_VALUES: 'VEHICLES_GROUP_LIST_VALUES',
  VEHICLES_ENGINE_TYPE_LIST_VALUES: 'VEHICLES_ENGINE_TYPE_LIST_VALUES',
  VEHICLES_STATION_LIST_VALUES: 'VEHICLES_STATION_LIST_VALUES',

  MAP_STATION_INFO_VALUES: 'MAP_STATION_INFO_VALUES',
  STATION_ROLE_LIST_VALUES: 'STATION_ROLE_LIST_VALUES',
  STATION_PERMISSION_VALUES: 'STATION_PERMISSION_VALUES',




  TERMINAL_LIST_VALUES: 'TERMINAL_LIST_VALUES',

  ALL_PASSENGER_LIST_VALUES: 'ALL_PASSENGER_LIST_VALUES',
  ALL_REGION_LIST_VALUES: 'ALL_REGION_LIST_VALUES',
  ALL_Vehicle_LIST_VALUES: 'ALL_Vehicle_LIST_VALUES',

  ALL_REGION_Working_LIST_VALUES: 'ALL_REGION__Working_LIST_VALUES',
  ALL_SHIFT_LIST_VALUES: 'ALL_SHIFT_LIST_VALUES',
  ALL_GROUP_BY_REGION_LIST_VALUES: 'ALL_GROUP_BY_REGION_LIST_VALUES',
  WORKING_CARS_DAYS_LIST_VALUES: 'WORKING_CARS_DAYS_LIST_VALUES',
  SHIT_EDIT_DETSILS:"SHIT_EDIT_DETSILS",


}

export { QUERIES }
